### ISSUE TITLE
bridge issues

### ISSUE THREAD

**Issue by Codyblaze** [dxzenith/eclipse-testnet#1]
when code gets to bridge part, after inputting solana address and private key...it cant continue bridge but brings up an error that its an invalid private key.
Pls look into this

**Comment by dxzenith** [comment]
![image](https://github.com/dxzenith/eclipse-testnet/assets/161211651/609f6f27-b37a-4573-9bf6-691399f192ba)
 Eclipse team updated their code yesterday, that is why we all are facing problem. 
 
 Gonna fix it

**Comment by Codyblaze** [comment]
Thank you very much...Pls update us once the fix is done
we appreciate your efforts

**Comment by dxzenith** [comment]
Updated, you can now run without any problem

**Comment by Codyblaze** [comment]
![Welcome-codespaces-blank-Codespaces-crispy-chainsaw-Visual-Studio-Code](https://github.com/dxzenith/eclipse-testnet/assets/65623201/662297fc-5dbc-4479-84c2-84a385a0c38e)

Returned an error while trying to mint token
